create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  city text not null, title text not null, distance_range text not null default '0–30 km',
  motivation text not null default 'Turismo', highlights text not null default '',
  access text not null default 'Asfalto', difficulty text not null default 'Fácil',
  best_time text not null default '', status text not null default 'planned' check (status in ('planned','completed')),
  visit_date date, total_km integer, rating integer check (rating between 1 and 5), notes text not null default '',
  sort_order integer not null default 999, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(owner_id,city,title)
);
create table if not exists public.trip_photos (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  path text not null unique, caption text not null default '', created_at timestamptz not null default now()
);
alter table public.trips enable row level security;
alter table public.trip_photos enable row level security;
create policy "public reads trips" on public.trips for select to anon, authenticated using (true);
create policy "owner creates trips" on public.trips for insert with check (auth.uid()=owner_id);
create policy "owner updates trips" on public.trips for update using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "owner deletes trips" on public.trips for delete using (auth.uid()=owner_id);
create policy "public reads photo records" on public.trip_photos for select to anon, authenticated using (true);
create policy "owner creates photos" on public.trip_photos for insert with check (auth.uid()=owner_id);
create policy "owner deletes photos" on public.trip_photos for delete using (auth.uid()=owner_id);
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('trip-photos','trip-photos',true,8000000,array['image/jpeg','image/png','image/webp','image/heic'])
on conflict (id) do update set public=true,file_size_limit=8000000;
create policy "owner uploads stored photos" on storage.objects for insert with check (bucket_id='trip-photos' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "owner deletes stored photos" on storage.objects for delete using (bucket_id='trip-photos' and (storage.foldername(name))[1]=auth.uid()::text);
