let trips=[],active=null;requireAuth().then(session=>{if(session)init()});
async function init(){await load();const q=new URLSearchParams(location.search);if(q.get('id'))openTrip(Number(q.get('id')),q.has('complete'))}
async function load(){const {data,error}=await blSupabase.from('trips').select('*,trip_photos(*)').order('sort_order').order('city');if(error)return alert(error.message);trips=data||[];renderList()}
function renderList(){const q=adminSearch.value.toLowerCase();tripList.innerHTML=trips.filter(t=>`${t.city} ${t.title}`.toLowerCase().includes(q)).map(t=>`<button data-id="${t.id}" class="${active?.id===t.id?'active':''}"><span>${t.status==='completed'?'✓':'○'}</span><div><b>${esc(t.title)}</b><small>${esc(t.city)} · ${esc(t.distance_range)}</small></div></button>`).join('');tripList.querySelectorAll('button').forEach(b=>b.onclick=()=>openTrip(Number(b.dataset.id)))}
function openTrip(id,complete=false){active=trips.find(t=>t.id===id);openForm(active,complete);renderList()}
function openForm(t=null,complete=false){editor.innerHTML='';editor.append(formTemplate.content.cloneNode(true));const form=tripForm;if(t){formHeading.textContent='Editar viagem';deleteBtn.classList.remove('hidden');for(const [k,v] of Object.entries(t)){if(form.elements[k])form.elements[k].value=v??''}if(complete){form.status.value='completed';if(!form.visit_date.value)form.visit_date.value=new Date().toISOString().slice(0,10)}renderPhotos(t.trip_photos||[])}else{active=null;form.access.value='Asfalto';form.difficulty.value='Fácil';form.status.value='planned'}form.onsubmit=save;deleteBtn.onclick=remove;photoInput.onchange=()=>photoInput.nextElementSibling.textContent=`${photoInput.files.length} foto(s) selecionada(s)`}
async function save(e){e.preventDefault();const form=e.currentTarget,btn=form.querySelector('.primary');btn.disabled=true;formError.textContent='';try{const f=new FormData(form);const row={owner_id:(await blSupabase.auth.getUser()).data.user.id,city:f.get('city').trim(),title:f.get('title').trim(),distance_range:f.get('distance_range'),motivation:f.get('motivation')||'Turismo',highlights:f.get('highlights')||'',access:f.get('access')||'Asfalto',difficulty:f.get('difficulty'),best_time:f.get('best_time')||'',status:f.get('status'),visit_date:f.get('visit_date')||null,total_km:f.get('total_km')?Number(f.get('total_km')):null,rating:f.get('rating')?Number(f.get('rating')):null,notes:f.get('notes')||''};let id=active?.id;if(id){const {error}=await blSupabase.from('trips').update(row).eq('id',id);if(error)throw error}else{const {data,error}=await blSupabase.from('trips').insert(row).select().single();if(error)throw error;id=data.id}await uploadPhotos(id,photoInput.files);await load();openTrip(id)}catch(err){formError.textContent=err.message||'Não foi possível salvar.'}finally{btn.disabled=false}}
async function uploadPhotos(tripId,files){const user=(await blSupabase.auth.getUser()).data.user;for(const file of files){if(file.size>8e6)throw new Error(`${file.name} excede 8 MB.`);const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${user.id}/${tripId}/${crypto.randomUUID()}-${safe}`;const {error}=await blSupabase.storage.from('trip-photos').upload(path,file);if(error)throw error;const r=await blSupabase.from('trip_photos').insert({trip_id:tripId,owner_id:user.id,path});if(r.error)throw r.error}}
async function renderPhotos(items){photoGallery.innerHTML='';for(const p of items){const url=await photoUrl(p.path);photoGallery.insertAdjacentHTML('beforeend',`<figure><img src="${url}" alt="Foto da viagem"><button type="button" data-photo="${p.id}" data-path="${p.path}">×</button></figure>`)}photoGallery.querySelectorAll('button').forEach(b=>b.onclick=()=>removePhoto(Number(b.dataset.photo),b.dataset.path))}
async function removePhoto(id,path){if(!confirm('Remover esta fotografia?'))return;await blSupabase.storage.from('trip-photos').remove([path]);await blSupabase.from('trip_photos').delete().eq('id',id);await load();openTrip(active.id)}
async function remove(){if(!active||!confirm(`Excluir “${active.title}” e suas fotos?`))return;const paths=(active.trip_photos||[]).map(p=>p.path);if(paths.length)await blSupabase.storage.from('trip-photos').remove(paths);await blSupabase.from('trips').delete().eq('id',active.id);active=null;await load();editor.innerHTML='<div class="emptyEditor"><span class="logo big">BL</span><h2>Viagem excluída</h2></div>'}
async function importSeed(){if(!confirm('Importar os 52 destinos do documento? Registros já existentes serão preservados.'))return;seedBtn.disabled=true;try{const seed=await fetch('data/trips.json').then(r=>r.json()),user=(await blSupabase.auth.getUser()).data.user;const rows=seed.map((t,i)=>({...t,owner_id:user.id,sort_order:i+1}));const {error}=await blSupabase.from('trips').upsert(rows,{onConflict:'owner_id,city,title',ignoreDuplicates:true});if(error)throw error;await load();alert(`${trips.length} destinos disponíveis.`)}catch(e){alert(e.message)}finally{seedBtn.disabled=false}}
newBtn.onclick=()=>openForm();seedBtn.onclick=importSeed;adminSearch.oninput=renderList;function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
