let trips=[],filterStatus="all"; requireAuth().then(session=>{if(session)load()});
const els={total:document.getElementById('total'),allCount:document.getElementById('allCount'),done:document.getElementById('done'),photos:document.getElementById('photos'),search:document.getElementById('search'),distance:document.getElementById('distance'),reason:document.getElementById('reason'),cards:document.getElementById('cards'),empty:document.getElementById('empty')};
async function load(){const {data,error}=await blSupabase.from("trips").select("*,trip_photos(id,path,caption)").order("sort_order").order("city");if(error)return showError(error.message);trips=data||[];renderStats();render()}
function renderStats(){els.total.textContent=trips.length;els.allCount.textContent=trips.length;els.done.textContent=trips.filter(t=>t.status==='completed').length;els.photos.textContent=trips.reduce((n,t)=>n+(t.trip_photos?.length||0),0)}
function match(t){const q=els.search.value.toLowerCase();return(filterStatus==='all'||t.status===filterStatus)&&(!els.distance.value||t.distance_range===els.distance.value)&&(!els.reason.value||t.motivation.includes(els.reason.value))&&`${t.city} ${t.title} ${t.motivation} ${t.highlights}`.toLowerCase().includes(q)}
async function render(){const list=trips.filter(match);els.cards.innerHTML=list.map(t=>card(t)).join('');els.empty.classList.toggle('hidden',!!list.length);for(const t of list){const p=t.trip_photos?.[0];if(p){const img=document.querySelector(`[data-photo="${p.id}"]`);if(img)img.src=await photoUrl(p.path)}}}
function card(t){const p=t.trip_photos?.[0];return`<article class="tripCard ${t.status}">${p?`<img data-photo="${p.id}" class="cardPhoto" alt="Foto de ${esc(t.title)}">`:''}<div class="cardTop"><span>${esc(t.distance_range)}</span><a href="admin.html?id=${t.id}" aria-label="Editar">•••</a></div><small>${esc(t.city)}</small><h3>${esc(t.title)}</h3><b class="motivation">${esc(t.motivation)}</b><p>${esc(t.highlights)}</p><div class="chips"><span>↗ ${esc(t.access)}</span><span>◇ ${esc(t.difficulty)}</span><span>◷ ${esc(t.best_time)}</span></div>${t.status==='completed'?`<div class="memory"><b>✓ Conhecemos${t.visit_date?' em '+new Date(t.visit_date+'T12:00:00').toLocaleDateString('pt-BR'):''}</b>${t.notes?`<p>“${esc(t.notes)}”</p>`:''}${t.rating?`<span>${'★'.repeat(t.rating)}</span>`:''}</div>`:`<a class="register" href="admin.html?id=${t.id}&complete=1">♡ Registrar esta viagem</a>`}</article>`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function showError(m){els.cards.innerHTML=`<p class="error">Não foi possível carregar: ${esc(m)}</p>`}
els.search.oninput=render;els.distance.onchange=render;els.reason.onchange=render;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.tabs .active').classList.remove('active');b.classList.add('active');filterStatus=b.dataset.status;render()});
